# Generated by Django 2.0 on 2019-07-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190708_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('bj', '北京'), ('sh', '上海'), ('sz', '深圳')], max_length=64),
        ),
    ]
