# Generated by Django 2.0 on 2019-07-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190708_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('sz', '深圳'), ('bj', '北京'), ('sh', '上海')], max_length=64),
        ),
    ]
