# Generated by Django 2.0 on 2019-07-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190708_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('bj', '北京'), ('sz', '深圳'), ('sh', '上海')], max_length=64),
        ),
    ]
