# Generated by Django 2.0 on 2019-07-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190708_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.IntegerField(choices=[(0, '全部'), (1, '男'), (2, '女')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('sh', '上海'), ('sz', '深圳'), ('bj', '北京')], max_length=64),
        ),
    ]
