# Generated by Django 2.0 on 2019-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190708_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('dl', '大连'), ('cd', '成都'), ('sh', '上海'), ('sz', '深圳'), ('gz', '广州'), ('bj', '北京')], max_length=64),
        ),
    ]
