# Generated by Django 2.0 on 2019-07-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190708_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('cd', '成都'), ('gz', '广州'), ('bj', '北京'), ('sh', '上海'), ('dl', '大连'), ('sz', '深圳')], max_length=64),
        ),
    ]
