# Generated by Django 2.0 on 2019-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190708_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('dl', '大连'), ('sz', '深圳'), ('bj', '北京'), ('sh', '上海'), ('cd', '成都'), ('gz', '广州')], max_length=64),
        ),
    ]
