# Generated by Django 2.0 on 2019-07-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190709_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('dl', '大连'), ('bj', '北京'), ('gz', '广州'), ('sz', '深圳'), ('sh', '上海'), ('cd', '成都')], max_length=64),
        ),
    ]
